catalog:
  "@antfu/eslint-config": ^4.13.0
  "@babel/parser": ^7.27.2
  "@babel/standalone": ^7.27.2
  "@babel/traverse": ^7.27.1
  "@commitlint/cli": ^19.8.1
  "@commitlint/config-conventional": ^19.8.1
  "@commitlint/types": ^19.8.1
  "@docusaurus/core": ^3.7.0
  "@docusaurus/module-type-aliases": ^3.7.0
  "@docusaurus/preset-classic": ^3.7.0
  "@docusaurus/theme-live-codeblock": ^3.7.0
  "@docusaurus/tsconfig": ^3.7.0
  "@docusaurus/types": ^3.7.0
  "@emotion/eslint-plugin": ^11.12.0
  "@emotion/styled": ^11.13.0
  "@eslint/compat": ^1.2.9
  "@eslint-react/eslint-plugin": ^1.49.0
  "@fontsource/inter": ^5.1.0
  "@mdx-js/react": ^3.0.0
  "@mui/joy": ^5.0.0-beta.52
  "@tanstack/eslint-plugin-query": ^5.74.7
  "@total-typescript/ts-reset": ^0.6.1
  "@tsconfig/node-ts": ^23.6.1
  "@tsconfig/strictest": ^2.0.5
  "@types/babel__core": ^7.20.5
  "@types/babel__standalone": ^7.1.9
  "@types/babel__traverse": ^7.20.7
  "@types/fs-extra": ^11.0.4
  "@types/lint-staged": ^13.3.0
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  "@vp-tw/eslint-config": ^0.1.1
  "@vp-tw/tsconfig": ^3.0.0
  babel-plugin-react-compiler: ^19.1.0-rc.1
  clsx: ^2.0.0
  commitizen: ^4.3.1
  cspell: ^9.0.1
  defu: ^6.1.4
  es-toolkit: ^1.31.0
  eslint: ^9.26.0
  eslint-config-prettier: ^10.1.5
  eslint-plugin-package-json: ^0.31.0
  eslint-plugin-react-compiler: ^19.1.0-rc.1
  fast-glob: ^3.3.3
  fs-extra: ^11.3.0
  husky: ^9.1.7
  jiti: ^2.4.2
  lint-staged: ^15.5.2
  npm-run-all: ^4.1.5
  pathe: ^2.0.3
  postcss-styled-syntax: ^0.7.1
  prettier: ^3.5.3
  prism-react-renderer: ^2.3.0
  react: ^19.0.0
  react-dom: ^19.0.0
  react-live: ^4.1.8
  stylelint: ^16.19.1
  stylelint-config-idiomatic-order: ^10.0.0
  stylelint-config-standard: ^38.0.0
  stylelint-prettier: ^5.0.3
  tsx: ^4.19.4
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unplugin: ^2.3.2
  vitest: ^2.1.3
onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - unrs-resolver
packages:
  - packages/*
